(function(){
  const all=Array.isArray(window.SCHOOLS)?window.SCHOOLS:[]; const pageSize=24; let page=1;
  const state={q:'',department:'',city:'',category:'',sort:'name'};
  const $=id=>document.getElementById(id);
  const unique=key=>[...new Set(all.map(x=>x[key]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
  function fill(id,values){const el=$(id); values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)})}
  fill('departmentFilter',unique('departamento')); fill('cityFilter',unique('ciudad')); fill('categoryFilter',unique('categoría'));
  $('heroCount').textContent=all.length.toLocaleString('es-CO'); $('heroCities').textContent=unique('ciudad').length; $('heroDepartments').textContent=unique('departamento').length;
  function getFiltered(){let rows=all.filter(x=>{const hay=[x.nombre,x.ciudad,x.departamento,x.categoría,x.dirección,x.servicios].join(' ').toLocaleLowerCase('es'); return (!state.q||hay.includes(state.q.toLocaleLowerCase('es')))&&(!state.department||x.departamento===state.department)&&(!state.city||x.ciudad===state.city)&&(!state.category||x.categoría===state.category)}); const key=state.sort==='city'?'ciudad':state.sort==='department'?'departamento':'nombre'; return rows.sort((a,b)=>a[key].localeCompare(b[key],'es')||a.nombre.localeCompare(b.nombre,'es'))}
  function escape(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function render(){const rows=getFiltered(), total=rows.length, pages=Math.max(1,Math.ceil(total/pageSize)); if(page>pages)page=pages; const start=(page-1)*pageSize; const visible=rows.slice(start,start+pageSize); $('resultSummary').textContent=`${total.toLocaleString('es-CO')} resultado${total===1?'':'s'} encontrado${total===1?'':'s'}`; $('directoryGrid').innerHTML=visible.map(x=>`<article class="school-card"><div class="card-top"><span class="card-id">#${String(x.id).padStart(4,'0')}</span><span class="category">${escape(x.categoría)}</span></div><h3>${escape(x.nombre)}</h3><div class="location"><span>⌖</span><span>${escape(x.ciudad)}, ${escape(x.departamento)}</span></div>${x.servicios?`<p class="card-services">${escape(x.servicios)}</p>`:''}<div class="card-actions">${x.ficha_url?`<a class="card-action primary" href="${x.ficha_url}">Ver ficha ↗</a>`:''}${x['Google Maps']?`<a class="card-action" href="${x['Google Maps']}" target="_blank" rel="noopener">Mapa ↗</a>`:''}${x.teléfono?`<a class="card-action" href="tel:${escape(x.teléfono)}">☎ ${escape(x.teléfono)}</a>`:''}</div></article>`).join(''); $('emptyState').hidden=visible.length!==0; renderChips(); renderPages(pages);}
  function renderChips(){const values=[['q',state.q],['department',state.department],['city',state.city],['category',state.category]].filter(x=>x[1]); $('activeFilters').innerHTML=values.map(([key,val])=>`<span class="chip">${escape(key==='q'?`“${val}”`:val)} <button type="button" data-clear="${key}" aria-label="Quitar filtro">×</button></span>`).join(''); document.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{state[b.dataset.clear]='';sync();render()})}
  function renderPages(pages){const nav=$('pagination'); if(pages<=1){nav.innerHTML='';return} let html=`<button class="page-button" data-page="${page-1}" ${page===1?'disabled':''}>←</button>`; const nums=[]; for(let i=1;i<=pages;i++){if(i===1||i===pages||Math.abs(i-page)<=2)nums.push(i); else if(nums[nums.length-1]!=='…')nums.push('…')} nums.forEach(n=>html+=n==='…'?'<span class="page-button" aria-hidden="true">…</span>':`<button class="page-button ${n===page?'active':''}" data-page="${n}">${n}</button>`); html+=`<button class="page-button" data-page="${page+1}" ${page===pages?'disabled':''}>→</button>`; nav.innerHTML=html; nav.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=Number(b.dataset.page);render();document.getElementById('directorio').scrollIntoView({behavior:'smooth',block:'start'})})}
  function sync(){ $('searchInput').value=state.q; $('departmentFilter').value=state.department; $('cityFilter').value=state.city; $('categoryFilter').value=state.category; $('sortSelect').value=state.sort; }
  $('searchInput').addEventListener('input',e=>{state.q=e.target.value.trim();page=1;render()}); $('clearSearch').onclick=()=>{state.q='';sync();page=1;render()}; $('departmentFilter').onchange=e=>{state.department=e.target.value;page=1;render()}; $('cityFilter').onchange=e=>{state.city=e.target.value;page=1;render()}; $('categoryFilter').onchange=e=>{state.category=e.target.value;page=1;render()}; $('sortSelect').onchange=e=>{state.sort=e.target.value;page=1;render()}; $('resetFilters').onclick=$('emptyReset').onclick=()=>{Object.assign(state,{q:'',department:'',city:'',category:''});page=1;sync();render()}; render();
})();
