(() => {
  const data = window.VETERINARIAS || [];
  const $ = (id) => document.getElementById(id);
  const state = { q: '', city: '', category: '', department: '', page: 1, perPage: 24 };
  const normalize = (v) => String(v || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const unique = (key) => [...new Set(data.map(x => x[key]).filter(Boolean))].sort((a,b) => a.localeCompare(b, 'es'));
  function fill(id, values) { const el=$(id); values.forEach(v => el.insertAdjacentHTML('beforeend', `<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`)); }
  function escapeHtml(v) { return String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
  fill('city', unique('ciudad')); fill('category', unique('categoria')); fill('department', unique('departamento'));
  function filtered() { const q=normalize(state.q); return data.filter(x => (!q || normalize(Object.values(x).join(' ')).includes(q)) && (!state.city || x.ciudad===state.city) && (!state.category || x.categoria===state.category) && (!state.department || x.departamento===state.department)); }
  function card(x) { const phone=(x.telefono||'').split(' / ')[0]; const wa=(x.whatsapp||'').split(' / ')[0]; return `<article class="card"><span class="badge">${escapeHtml(x.categoria || 'Servicio para mascotas')}</span><h3>${escapeHtml(x.nombre)}</h3>${x.servicios?`<p>${escapeHtml(x.servicios).slice(0,120)}${x.servicios.length>120?'…':''}</p>`:''}<p class="location">📍 ${escapeHtml([x.ciudad,x.departamento].filter(Boolean).join(' · ') || 'Colombia')}</p>${x.direccion?`<p class="address">${escapeHtml(x.direccion)}</p>`:''}<div class="card-actions"><a class="primary" href="fichas/${escapeHtml(x.slug)}/">Ver ficha</a>${phone?`<a href="tel:${phone.replace(/\s/g,'')}">Llamar</a>`:''}${wa?`<a href="${escapeHtml(wa)}" target="_blank" rel="noopener">WhatsApp</a>`:''}</div></article>`; }
  function render() { const list=filtered(), totalPages=Math.max(1,Math.ceil(list.length/state.perPage)); state.page=Math.min(state.page,totalPages); const start=(state.page-1)*state.perPage; $('cards').innerHTML=list.slice(start,start+state.perPage).map(card).join(''); $('empty').hidden=list.length>0; $('resultSummary').textContent=`${list.length.toLocaleString('es-CO')} resultados encontrados`; $('pageInfo').textContent=`Página ${state.page} de ${totalPages}`; $('prev').disabled=state.page<=1; $('next').disabled=state.page>=totalPages; document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>openDetail(list.find(x=>String(x.id)===b.dataset.detail)))); }
  function openDetail(x) { if(!x)return; const phone=(x.telefono||'').split(' / ')[0]; const wa=(x.whatsapp||'').split(' / ')[0]; $('modalContent').innerHTML=`<span class="badge">${escapeHtml(x.categoria)}</span><h2>${escapeHtml(x.nombre)}</h2><div class="detail-list"><div><strong>Ubicación</strong>${escapeHtml([x.direccion,x.ciudad,x.departamento].filter(Boolean).join(', ')||'Colombia')}</div>${x.servicios?`<div><strong>Servicios</strong>${escapeHtml(x.servicios)}</div>`:''}${x.telefono?`<div><strong>Teléfono</strong>${escapeHtml(x.telefono)}</div>`:''}${x.email?`<div><strong>Correo</strong>${escapeHtml(x.email)}</div>`:''}</div><div class="modal-actions">${phone?`<a href="tel:${phone.replace(/\s/g,'')}">Llamar ahora</a>`:''}${wa?`<a href="${escapeHtml(wa)}" target="_blank" rel="noopener">Contactar por WhatsApp</a>`:''}${x.google_maps?`<a href="${escapeHtml(x.google_maps)}" target="_blank" rel="noopener">Ver ubicación</a>`:''}</div>`; $('modal').hidden=false; } 
  const slugify = v => normalize(v).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  $('cityLinks').innerHTML=unique('ciudad').slice(0,60).map(v=>`<a href="ciudades/${slugify(v)}/">Veterinarias en ${escapeHtml(v)}</a>`).join('');
  $('search').addEventListener('input',e=>{state.q=e.target.value;state.page=1;render()}); $('searchBtn').addEventListener('click',()=>document.getElementById('directorio').scrollIntoView({behavior:'smooth'}));
  [['city','city'],['category','category'],['department','department']].forEach(([id,key])=>$(id).addEventListener('change',e=>{state[key]=e.target.value;state.page=1;render()}));
  $('clearFilters').addEventListener('click',()=>{state.city=state.category=state.department='';['city','category','department'].forEach(id=>$(id).value='');state.page=1;render()}); $('prev').addEventListener('click',()=>{state.page--;render();window.scrollTo({top:500,behavior:'smooth'})}); $('next').addEventListener('click',()=>{state.page++;render();window.scrollTo({top:500,behavior:'smooth'})}); $('filterToggle').addEventListener('click',()=>$('filters').classList.toggle('open')); document.querySelectorAll('[data-quick]').forEach(b=>b.addEventListener('click',()=>{state.q=b.dataset.quick;$('search').value=state.q;state.page=1;render();document.getElementById('directorio').scrollIntoView({behavior:'smooth'})})); document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>{$('modal').hidden=true})); render();
})();
